version: '3.8'

services:
  frontend:
    build:
      context: ./Front-end
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    depends_on:
      - backend
    networks:
      - helpdesk-network

  backend:
    build:
      context: ./Back-end
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_H2_CONSOLE_ENABLED: "true"
      SPRING_H2_CONSOLE_PATH: "/h2-console"
      SPRING_DATASOURCE_URL: "jdbc:h2:mem:testedb"
      SPRING_DATASOURCE_USERNAME: "sa"
      SPRING_DATASOURCE_PASSWORD: ""
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: "org.h2.Driver"
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL: "true"
    networks:
      - helpdesk-network

networks:
  helpdesk-network:
    driver: bridge
